# Generated by Django 2.2.7 on 2020-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200416_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
